### PR TITLE
docs: update README.md to mention complete list of paths

### PR DESCRIPTION
**Pull request by jovanspassport**
Added more detailed explanation for changing the /package folder name.

### CODE REVIEW

**Review by jenstroeger — APPROVED** [review]
Great, thanks @jovanspassport!

**Comment by jenstroeger** [comment]
Sorry, @jovanspassport, I wanted to fix the commit lint by fixing the PR title and I didn’t remember that the actual commit message must match. Would you mind amending your commit https://github.com/jenstroeger/python-package-template/pull/33/commits/0f6e7af38fc5001c7c496feed6e1dded3d38931b with the subject equal to this PR title? (Note: lower-case and present tense.)

**Comment by jenstroeger** [comment]
Also, on second thought I think `docs:` might suit better than `chore:` in this case 🤔

**Comment by jovanspassport** [comment]
@jenstroeger I changed the commit message.

**Pull request merged**
