### PR TITLE
chore: rename README and CHANGELOG files to make merging forks easier

### PR DESCRIPTION
**Pull request by jenstroeger**
This PR closes https://github.com/jenstroeger/python-package-template/issues/30 and closes https://github.com/jenstroeger/python-package-template/issues/31.

I’ve followed the latest https://github.com/jenstroeger/python-package-template/issues/30#issuecomment-963803757 in our conversation: symlink the `README.md` to a `TEMPLATE_README.md` and add a `TEMPLATE_CHANGELOG.md`. Users who fork can then follow these instructions:

> Change the `LICENSE.md` file and the badge according to your needs, replace the [symbolic link](https://en.wikipedia.org/wiki/Symbolic_link) `README.md` with an actual README file, and edit the `pyproject.toml` file to change this line: `changelog_file = "CHANGELOG.md"`.

There’s still that change to the `pyproject.toml` file folks need to deal with, but that seems like a manageable one.

Change to the [reorg-meta-files](https://github.com/jenstroeger/python-package-template/tree/reorg-meta-files) branch and you’ll see the symlink working 🤓 No git config changes required because [`core.symlink = true`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresymlinks) is the default.

### CODE REVIEW

**Comment by acrobat888** [comment]
Why wouldn't you want the CHANGELOG.md file to be a symbolic link as well and in the instructions, vs. having a "blank" CHANGELOG.md file?

**Comment by jenstroeger** [comment]
> Why wouldn't you want the CHANGELOG.md file to be a symbolic link as well and in the instructions, vs. having a "blank" CHANGELOG.md file?

Because Github seems to care about `README.md` but not about `CHANGELOG.md`. So, having an empty `CHANGELOG.md` ready for the user and another `TEMPLATE_CHANGELOG.md` for this repo (at the expense of configuring it) seemed easier. But maybe you’re right, another symlink might make more sense?

**Comment by acrobat888** [comment]
👍

**Comment by jenstroeger** [comment]
See commit https://github.com/jenstroeger/python-package-template/pull/35/commits/d127440e3a4e588d04e037ebbdbb0231fffd2bc3.

I’m curious if Github when updating the `CHANGELOG.md` as part of executing an Action will follow the symlink 🤔

**Review by behnazh — COMMENTED** [review]
I'm not sure using templates for `README.md` and `CHANGELOG.md` make sense. They serve as the actual `README` and `CHANGELOG` files for this template repo and are not trying to show users how to create `README` or `CHANGELOG`. The current workaround of using symlinks and templates would be confusing to users IMO.

**Comment by jenstroeger** [comment]
@behnazh, the problem is that when people fork this repository and have their own `README.md` and `CHANGELOG.md` files, and then update their forks with upstream changes from this repo they will receive heaps of merge conflicts with these two files — because this repo’s README and CHANGELOG continues to change separately from the forked README and CHANGELOG.

Which is why @acrobat888 suggested the separate template files. But having separate template files means that Github won’t find this repo’s README (now called `TEMPLATE_README.md`) and that’s what the symlinks do.

The ultimate goal is to make merging changes to this repo into a forked repo as easy as possible.

What’s your suggestion to tackle that?

**Comment by behnazh** [comment]
> The ultimate goal is to make merging changes to this repo into a forked repo as easy as possible.
> 
> What’s your suggestion to tackle that?

I understand the problem and definitely agree that it should be resolved. I just find using templates here inappropriate because `TEMPLATE_README.md` and `TEMPLATE_CHANGELOG.md` are not really templates.

I would prefer the [alternative ways you discussed](https://github.com/jenstroeger/python-package-template/issues/30#issuecomment-963600344), and suggested in the [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#about-readmes):
> If you put your README file in your repository's root, docs, or hidden .github directory, GitHub will recognize and automatically surface your README to repository visitors.

**Comment by jenstroeger** [comment]
> I understand the problem and definitely agree that it should be resolved. I just find using templates here inappropriate because `TEMPLATE_README.md` and `TEMPLATE_CHANGELOG.md` are not really templates.

What if we called these two files `UPSTREAM_README.md` and `UPSTREAM_CHANGELOG.md`? That would reflect where they belong — to the fork’s `upstream` remote.

> I would prefer the [alternative ways you discussed](https://github.com/jenstroeger/python-package-template/issues/30#issuecomment-963600344), and suggested in the [GitHub documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#about-readmes):

Personally, [I don’t mind either way](https://www.youtube.com/watch?v=CxK_nA2iVXw) though the symlink solution seams to have the least impact beyond changes to these two files.

**Comment by behnazh** [comment]
> What if we called these two files `UPSTREAM_README.md` and `UPSTREAM_CHANGELOG.md`? That would reflect where they belong — to the fork’s `upstream` remote.

These file names look better :+1:

**Comment by jenstroeger** [comment]
Commit https://github.com/jenstroeger/python-package-template/pull/35/commits/7be04b3951b22058bacb31740fd88d05a9a596e0. @acrobat888, are you ok with this approach?

**Review by behnazh — APPROVED** [review]

**Pull request merged**
