### PR TITLE
chore(dev): bump black pre-commit hook from 21.12b0 to 22.3.0

### PR DESCRIPTION
**Pull request by behnazh**

### CODE REVIEW

**Review by jenstroeger — CHANGES_REQUESTED** [review]
Can you please also update this line:

https://github.com/jenstroeger/python-package-template/blob/1d7ab62da35cf2e211bd154832aa33293bde5cb5/.pre-commit-config.yaml#L40

**Comment by jenstroeger** [comment]
@behnazh thank you for the PR. Looking at the [failing](https://github.com/jenstroeger/python-package-template/runs/5727102958?check_suite_focus=true) run I agree with you that the [click](https://github.com/pallets/click) package is the culprit.

There are two related problems with this scenario:
- This morning Click shipped [v8.1.0](https://github.com/pallets/click/releases/tag/8.1.0) which they say is a feature release (minor version update) which removes deprecated features — I would expect that to be a _breaking change_ and therefore a _major_ version update.
- Black specifies its dependency of click [like so](https://github.com/psf/black/blob/ae2c0758c9e61a385df9700dc9c231bf54887041/setup.py#L99): `click>=8.0.0` which makes it vulnerable to picking up a breaking change and thus break itself.
- Black fails because it attempts a `from click import _unicodefun` which is a private symbol by convention so that’s fragile anyway.

Welcome to version hell once more 🤓

**Comment by behnazh** [comment]
> Can you please also update this line:
> 
> https://github.com/jenstroeger/python-package-template/blob/1d7ab62da35cf2e211bd154832aa33293bde5cb5/.pre-commit-config.yaml#L40

Done.

**Comment by behnazh** [comment]
> @behnazh thank you for the PR. Looking at the [failing run](https://github.com/jenstroeger/python-package-template/runs/5727102958?check_suite_focus=true) I agree with you that the [click](https://github.com/pallets/click) package is the culprit, but not alone.
> 
> There are three related problems with this scenario:
> 
>     * This morning Click shipped [v8.1.0](https://github.com/pallets/click/releases/tag/8.1.0) which they say is a feature release (minor version update) which removes deprecated features — I would expect that to be a _breaking change_ and therefore a _major_ version update.
> 
>     * Black specifies its dependency of click [like so](https://github.com/psf/black/blob/ae2c0758c9e61a385df9700dc9c231bf54887041/setup.py#L99): `click>=8.0.0` which makes it vulnerable to picking up a breaking change and thus break itself.
> 
>     * Black fails because it attempts a `from click import _unicodefun` which is a private symbol by convention so that’s fragile anyway.
> 
> 
> Welcome to version hell once more nerd_face

I'm not looking forward to it :wink:

**Pull request merged**
