### PR TITLE
ci: rename `RELEASE_TOKEN` secret to `REPO_ACCESS_TOKEN`

### PR DESCRIPTION
**Pull request by jenstroeger**
As we discussed in https://github.com/jenstroeger/python-package-template/pull/224#discussion_r903168645.

### CODE REVIEW

**Review by behnazh — CHANGES_REQUESTED** [review]
Can you please document how to set `secrets.REPO_ACCESS_TOKEN` and which scopes to :heavy_check_mark: ?

**Comment by jenstroeger** [comment]
> Can you please document how to set `secrets.REPO_ACCESS_TOKEN` and which scopes to ✔️ ?

Isn’t that in the README change? Did I miss something?

**Comment by behnazh** [comment]
> > Can you please document how to set `secrets.REPO_ACCESS_TOKEN` and which scopes to heavy_check_mark ?
> 
> Isn’t that in the README change? Did I miss something?

You don't specify which boxes to :heavy_check_mark: under `repo`.

**Comment by jenstroeger** [comment]
> You don't specify which boxes to ✔️ under `repo`.

How about this (commit https://github.com/jenstroeger/python-package-template/pull/231/commits/a43f856ea071ee4de34f37f222348ad5c1171b9b):

> Create a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) (PAT) for your Github user account with [`repo` scope](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes) (including _all_ of the `repo` permissions), and then [create a secret](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) for the new Github repository with the name `REPO_ACCESS_TOKEN` whose value is that new PAT. This secret is important for some of the [Github Workflows](https://github.com/jenstroeger/python-package-template/tree/main/.github/workflows) in this repository.

**Review by behnazh — APPROVED** [review]

**Pull request merged**
