### PR TITLE
chore: add security policy, elaborate on test policy

### PR DESCRIPTION
**Pull request by jenstroeger**
Based on code-scanning feedback for https://github.com/jenstroeger/python-package-template/security/code-scanning/36 and issue https://github.com/jenstroeger/python-package-template/issues/13, this change [adds a security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) to our template repo.

### CODE REVIEW

**Comment by jenstroeger** [comment]
…we should probably do with `SECURITY.md` what we did with `README.md` and `CHANGELOG.md` — make it a [symlink](https://en.wikipedia.org/wiki/Symbolic_link) to `UPSTREAM_SECURITY.md` 🤔

**Comment by jenstroeger** [comment]
…we should probably do with `SECURITY.md` what we did with `README.md` and `CHANGELOG.md` — make it a [symlink](https://en.wikipedia.org/wiki/Symbolic_link) to `UPSTREAM_SECURITY.md` 🤔

**Comment by behnazh** [comment]
> …we should probably do with `SECURITY.md` what we did with `README.md` and `CHANGELOG.md` — make it a [symlink](https://en.wikipedia.org/wiki/Symbolic_link) to `UPSTREAM_SECURITY.md` thinking

I wonder if Scorecards would be sensitive to names?

**Comment by jenstroeger** [comment]
> I wonder if Scorecards would be sensitive to names?

Or is able to follow symlinks 😉

**Comment by behnazh** [comment]
> > I wonder if Scorecards would be sensitive to names?
> 
> Or is able to follow symlinks wink

We will find out!

**Review by behnazh — APPROVED** [review]

**Comment by jenstroeger** [comment]
Hmm, is this PR a `chore:` (no version bump) or a `fix:` (patch version bump)?

**Review by behnazh — APPROVED** [review]

**Comment by behnazh-w** [comment]
> Hmm, is this PR a `chore:` (no version bump) or a `fix:` (patch version bump)?
`docs:` is not accepted?

**Comment by behnazh** [comment]
> Hmm, is this PR a `chore:` (no version bump) or a `fix:` (patch version bump)?

docs: is not accepted?

**Pull request merged**
